// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAre3TCaxhF9znn5qEFCVHd8hRuTAnHQuI',
    appId: '1:313775491917:web:4101f66262a666c38dc504',
    messagingSenderId: '313775491917',
    projectId: 'fir-c61da',
    authDomain: 'fir-c61da.firebaseapp.com',
    storageBucket: 'fir-c61da.firebasestorage.app',
    measurementId: 'G-PVZG8WXLKM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEP2wyPkkPZd8z63-EiS2a44TcpAmSzgg',
    appId: '1:313775491917:android:0d086f2379b04cdb8dc504',
    messagingSenderId: '313775491917',
    projectId: 'fir-c61da',
    storageBucket: 'fir-c61da.firebasestorage.app',
  );
}
