// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCf2PfER1lwZZLok-RRugbNTeMUCvYhDHg',
    appId: '1:8414776972:web:b221cfc4a411bd56cdf5a9',
    messagingSenderId: '8414776972',
    projectId: 'fir-demo-6a2fb',
    authDomain: 'fir-demo-6a2fb.firebaseapp.com',
    storageBucket: 'fir-demo-6a2fb.firebasestorage.app',
    measurementId: 'G-50M9GSZ1X4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCuOoCM2z8plekNemWX4fUEsXlptflEYs',
    appId: '1:8414776972:android:37b65101e6121dc1cdf5a9',
    messagingSenderId: '8414776972',
    projectId: 'fir-demo-6a2fb',
    storageBucket: 'fir-demo-6a2fb.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7WwDKIWjYPN9jARj9NEKRl2YDt0ZshbA',
    appId: '1:8414776972:ios:8a3a1158a7a76e2bcdf5a9',
    messagingSenderId: '8414776972',
    projectId: 'fir-demo-6a2fb',
    storageBucket: 'fir-demo-6a2fb.firebasestorage.app',
    iosClientId: '8414776972-qpt58r44u8gt6t6nesdcgthiqd9ag4mm.apps.googleusercontent.com',
    iosBundleId: 'com.example.demoFirebase',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7WwDKIWjYPN9jARj9NEKRl2YDt0ZshbA',
    appId: '1:8414776972:ios:8a3a1158a7a76e2bcdf5a9',
    messagingSenderId: '8414776972',
    projectId: 'fir-demo-6a2fb',
    storageBucket: 'fir-demo-6a2fb.firebasestorage.app',
    iosClientId: '8414776972-qpt58r44u8gt6t6nesdcgthiqd9ag4mm.apps.googleusercontent.com',
    iosBundleId: 'com.example.demoFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCf2PfER1lwZZLok-RRugbNTeMUCvYhDHg',
    appId: '1:8414776972:web:3bae790452980ad2cdf5a9',
    messagingSenderId: '8414776972',
    projectId: 'fir-demo-6a2fb',
    authDomain: 'fir-demo-6a2fb.firebaseapp.com',
    storageBucket: 'fir-demo-6a2fb.firebasestorage.app',
    measurementId: 'G-N1W2E9QBY5',
  );

}